
server.port=8080
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://localhost:5432/relising_items_db
spring.datasource.username=relising_items_admin
spring.datasource.password=diploma123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.boot.autoconfigure.orm.jpa=DEBUG

images.upload.base-dir=uploads/images
images.upload.ads-dir=ads
images.upload.avatars-dir=avatars
images.upload.max-file-size=10MB

logging.level.ru.skypro.homework.controller.AdvertisementsController=DEBUG
logging.level.ru.skypro.homework.service.impl.AdServiceImpl=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter=DEBUG

