
server.port=8080

spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:postgresql://localhost:5432/relising_items_DB
spring.datasource.username=relising_items_admin
spring.datasource.password=diploma123

server.address=0.0.0.0
